### PR TITLE
Translate Home Page

### PR DESCRIPTION
**Pull request by joaquimds**
Translating the home page requires:
  - Enable translation of tags (see https://docs.wagtail.org/en/stable/advanced_topics/i18n.html#translatable-snippets)
  - Update the tag cloud code to filter tags by locale
  - Update the sidebar code to only return pages in the current locale and display localized headings

These changes could potentially break things, so testing is required!

**To Test**

1. Make a copy of the live database and load it locally
2. Run the migrations
3. Create a translated version of a tag
4. Tag some localized pages with the localized tag
5. Check the homepage in that locale shows the localized tags and the correct pages in the sidebar

## How Will This Be Deployed?
We have to run the migrations.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- * I've checked the spec (e.g. Figma file) and documented any divergences.
- [x] My code follows the code style of this project.
- * My change requires a change to the documentation.
- * I've updated the documentation accordingly.

### CODE REVIEW

**Comment by janbaykara** [comment]
- On a high level, will there be editor UX issues like accidentally tagging an English page with a Portuguese tag? Or are tags deduped across translations (e.g. by their shared `translation_key`) for the purposes of filtering?
- By 'sidebar' I assume you mean the filtering system right?
- We'll also need to test this with the tag filtering for the map page / JS / api.

**Review by janbaykara — COMMENTED** [review]
Heroic work. I've not run this locally yet but I can't see anything that gives me flashing warning lights.

**Comment by janbaykara** [comment]
Reviewing this. Some docs on how I got the prod DB on my local:

```bash
# Get prod DB $CONNECTION_STRING from Digital Ocean database manager https://cloud.digitalocean.com/databases/c93ec41a-d218-4a6c-bf32-552d26428d38?i=8bfd6e
# Then dump the DB to local
pg_dump "$CONNECTION_STRING" > sf_prod.sql
# Add the following lines below the `SET` commands:
#   DROP SCHEMA public CASCADE;
#   CREATE SCHEMA public;
# And find/replace all `TO db` -> `TO postgres`
# (You might be better off using BBEdit for this as VSCode performs poorly with large text file edits)
# Then move the .sql file to the project directory
# In the vscode devcontainer
sudo apt-get install postgresql-client
psql -h db -U postgres < '/workspace/.devcontainer/sf_prod.sql'
```

**Review by janbaykara — CHANGES_REQUESTED** [review]
OK! This is working, which is fantastic. Just a few places to add the localised text.

All the below come from selecting the Portuguese translation, and translating Amazon Rainforest to Amazonia in Portuguese, but NOT tagging the localised page with the localised tag but rather just leaving it. Strangely that doesn't seem to stop the localised home page from showing the localised tag, which I think is intuitively the right behaviour.

## Page template's tag list should be localised

Screenshot 2023-06-08 at 10 23 45

## Tag sidepanel should be localized

(This might be the result of the previous thing.)

Screenshot 2023-06-08 at 10 25 08

## Localised tag does show when you select a locale, even if you don't tag a page with the localised version of the tag — this works as expected! ✅

Screenshot 2023-06-08 at 10 26 48

**Review by janbaykara — CHANGES_REQUESTED** [review]
## Tags in the MapView tag filter should be deduplicated and localized

When there are three locale variants of the same tag, dedupe and localise them (we use `set` for this elsewhere in the codebase).

Screenshot 2023-06-08 at 18 35 32

## Filtering by a translated tag on the map should work

Hard to explain but will make sense after the previous thing is solved.

## Filter UI on index pages doesn't show localised tags

Screenshot 2023-06-08 at 18 38 34

## Filtering on index page seems broken, actually

Unclear if this is an offshoot of the translation work though.

Screenshot 2023-06-08 at 18 39 36

## Semi-related, but autocompletion of tags ought to ignore capitals

Sorry, this is a bit of a tangent so feel free to push back if it seems really unrelatable, but I noticed you subclassed the tag manager widget and I wondered if we could ignore case when autocompleting, to avoid more duplicate tags, so we don't end up with more duplicates that lack translations?

Screenshot 2023-06-08 at 18 41 38

Screenshot 2023-06-08 at 18 41 33

**Comment by janbaykara** [comment]
- Map filter tags are still duplicated

**Comment by conatus** [comment]
Picking this up, here is my test plan to get this out of the door.

## Test Plan

- [ ] Setup up locally as per Jan's instructions
- [ ] Are the tags on the home page translated?
- [ ] Does the home page filter bar seem correct?
- [ ] Are the tags on individual pages only the tags within the locale we are in?
- [ ] Are the tags on the map only the tags within the locale we are in?
- [ ] Does the filter UI on the index pages accord to the locale we are in?
- [ ] Is the tag sidebar on all pages localised?

## Additional cleanup
-  [ ] Take a ticket for the issue with capitalisation named by Jan above

**Comment by conatus** [comment]
Right, successfully dumped the database into my local version.

Just to note that the password for Postgres user inside of the Devcontainer is `postgres`. The dump fails on the last line `GRANT INSERT,DELETE,UPDATE ON TABLE public.spatial_ref_sys TO doadmin WITH GRANT OPTION` but as this is seemingly to do with Digital Ocean and their adminstration of this database, I think this is okay.

**Comment by conatus** [comment]
I have realised the reason I wasn't seeing the interface is because I am on the wrong branch!

**Comment by conatus** [comment]
Looking at this now.

Screenshot 2023-07-17 at 14 56 11

Screenshot 2023-07-17 at 14 57 34

So we certainly see mixed content between languages.

This also works the other way. Here is Stories but in English.

Screenshot 2023-07-17 at 15 01 42

The problem is here we now see the same content in Spanish as we see in English.

e.g. http://localhost:8000/es/historias/la-forma-en-que-las-plataformas-digitales-transforman-las-actividades-de-restauraci%C3%B3n-de-selvas-a-nivel-global/

and then http://localhost:8000/en/stories/how-digital-platforms-transform-global-forest-restoration-actions/

Whereas what we want to see is, for example in Spanish, everything in English in Stories and any content in Spanish that is unique and any content in Spanish translated from English. I don't think this is too hard to do. In the loop extracting this, we need to check to see if something is a translation, and exclude the English versions from the listing where a translation exists.

**Comment by joaquimds** [comment]
@conatus That page is actually a *manual* translation of the English page - the two pages aren't linked at all >_< . We can't easily detect this, so we'll have to fix this manually in the admin system. Hopefully there are not many of these cases.

**Comment by joaquimds** [comment]
@conatus do you think we can merge? And I'll manually copy that content across on prod?

**Comment by conatus** [comment]
Replied on Linear, but basically if we have a properly translated page and only see it one time in an index, then this is good to go.

The interface copy is not translated. I assume because it simply...has not been translated.

**Pull request merged**
